---
title: "Authentic Visual Data Literacy: Project Page"
output: rmdformats::readthedown
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rmdformats)
```


# Introduction to the Project

The [2016 GAISE Guidelines](https://www.amstat.org/docs/default-source/amstat-documents/gaisecollege_full.pdf), in describing the collective thinking expressed in the statistics education literature about what a student should know and understand at the end of a first course in statistics, state that: 

- "Students should become critical consumers of statistically-based results reported in popular media, recognizing whether reported results reasonably follow from the study and analysis conducted", and
- "Students should be able to produce graphical displays and numerical summaries and interpret what graphs do and do not reveal". 

With data and graphical displays seeping into all facets of life, from news to entertainment, we could not agree more. However, graphs we see in our every day lives are often quite different than the graphs students are exposed to in introductory statistics courses. 

In this project, we investigate methods for both the assessment and instructions of these skills in students. 

<br>

# Assessment

In this phase of the project, we investigate whether students can interpret what *authentic* graphs they may see in their every day lives do and do not reveal, and how we can *measure* their skills in doing so. 

## Current Status

We have built and tested several assessment items and stems, and are in the process of publishing a manuscript detailing the assessment development process. 

## Project Contributors

In alphabetical order: 

- [Kelly Findley](https://kelly-findley.github.io/)
- Madeline Hunt
- Mia Petrie
- [V.N. Vimal Rao](https://raovnv.github.io/research.html)

## Funding

This project is supported by a grant from the University of Illinois Provost's Initiative for Teaching Advancement. 

## Presentations

Hunt, M., Findley, K., & Rao, V.N.V. (2026, June). [*Introducing the CLEAR Data Assessment to Evaluate Students' Visual Data Literacy*](https://github.com/RaoVNV/authenticliteracy/blob/main/URS%202026%20Hunt%20et%20al.pdf) [Poster Presentation]. Electronic Conference on Teaching Statistics. 

Petrie, M., Hunt, M., Rao, V.N.V., & Findley, K. (2025, July). [*"It's just quantitative": Exploring students' detection of biases in data visualizations*](https://github.com/RaoVNV/authenticliteracy/blob/main/URS%202025%20Petrie%20et%20al.pdf) [Poster Presentation]. United States Conference on Teaching Statistics, Ames, Iowa, USA.

Hunt, M., Petrie, M, Findley, K., & Rao, V.N.V. (2025, July). [*Challenges and opportunities for promoting visual data literacy*](https://github.com/RaoVNV/authenticliteracy/blob/main/URS%202025%20Hunt%20et%20al.pdf) [Poster Presentation]. United States Conference on Teaching Statistics, Ames, Iowa, USA. 

<br> 

# Instruction

In this phase of the project, we investigate whether students can interpret what *authentic* graphs they may see in their every day lives do and do not reveal, and how we can *develop* their skills in doing so.

## Current Status

We are currently evaluating two different activities in their efficacy to promote students' interpretations of graphs. One is the popular *What's going on in this graph?* activity published by the New York Times. The other is a classroom intervention built on the educational theory of anchoring.  

## Project Contributors

In alphabetical order: 

- Ava Graczyk
- Emily Buhnerkempe
- Madison King
- Reem Kharfan
- [V.N. Vimal Rao](https://raovnv.github.io/research.html)

## Presentations

King, M., Buhnerkempe, E., & Rao, V.N.V. (2026, June). [*Challenging Students to Think for Themselves*](https://github.com/RaoVNV/authenticliteracy/blob/main/URS%202026%20King%20et%20al.pdf) [Poster Presentation]. Electronic Conference on Teaching Statistics. 

Graczyk, A., Hunt, M., & Rao, V.N.V. (2026, June). [*Artificial Incompetence: AI's Failures in Interpreting Graphs*](https://github.com/RaoVNV/authenticliteracy/blob/main/URS%202026%20Graczyk%20et%20al.pdf) [Poster Presentation]. Electronic Conference on Teaching Statistics. 

Kharfan, R., Bailey, N., & Rao, V.N.V. (2025, July). [*Who's Not Here? Fostering a Statistical Literacy Habit of Mind*](https://github.com/RaoVNV/authenticliteracy/blob/main/URS%202025%20Kharfan%20et%20al.pdf) [Poster Presentation]. United States Conference on Teaching Statistics, Ames, Iowa, USA. 